networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_sttnil:
    image: xoxxox/envweb:001
    container_name: xoxxox_sttnil
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    ports:
    - 10101:80
    command: "python /opt/common/bin/xoxxox/srvstt.py --engine xoxxox/engine_sttnil"
